name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04  # Use Ubuntu 20.04 for better compatibility
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'  # Use Python 3.8 for better compatibility
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zip \
          unzip \
          openjdk-8-jdk \  # JDK 8 works better with Android tools
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev \
          git \
          python3-venv \
          python3-pip
        
    - name: Create virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        
    - name: Install Python dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install buildozer cython
        
    - name: Build APK with retry (may take 30+ minutes)
      run: |
        source venv/bin/activate
        # Buildozer will automatically download Android SDK and build tools
        buildozer android debug || buildozer android debug  # Try twice in case of timeouts
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: novel-downloader-apk
        path: bin/*.apk
