name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install Buildozer
      run: |
        pip install buildozer
        
    - name: Build with specific target (bypass license issues)
      run: |
        # Set environment variable to avoid license prompts
        export ANDROID_LICENSE_ACCEPTANCE=accept
        buildozer android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: novel-downloader-apk
        path: bin/*.apk
