name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4
      
    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to v5
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zip \
          unzip \
          openjdk-8-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev
        
    - name: Install Buildozer
      run: |
        pip install buildozer
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Build APK
      run: |
        buildozer android debug
        ls -la bin/
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: novel-downloader-apk
        path: bin/*.apk
