name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zip \
          unzip \
          openjdk-11-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses-dev \
          cmake \
          libffi-dev \
          libssl-dev \
          git \
          python3-venv \
          python3-pip \
          wget \
          curl
        
    - name: Create virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        
    - name: Install Python dependencies in virtual environment
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install buildozer cython
        
    - name: Build APK (Let Buildozer handle Android SDK automatically)
      run: |
        source venv/bin/activate
        # Buildozer will automatically download all required Android components
        buildozer -v android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: novel-downloader-apk
        path: bin/*.apk
