name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install basic dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-11-jdk git python3-pip
        
    - name: Install Buildozer
      run: |
        pip install buildozer
        
    - name: Build APK (Be patient - 30-45 minutes)
      run: |
        buildozer android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: novel-downloader-apk
        path: bin/*.apk
