name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zip \
          unzip \
          openjdk-11-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses-dev \
          cmake \
          libffi-dev \
          libssl-dev \
          git \
          python3-venv \
          python3-pip \
          wget \
          curl
        
    - name: Create virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        
    - name: Install Python dependencies in virtual environment
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install buildozer cython
        
    - name: Accept Android licenses before build
      run: |
        source venv/bin/activate
        # Initialize buildozer to create the directory structure
        buildozer init || true
        
        # Create the Android SDK directory structure
        mkdir -p ~/.buildozer/android/platform/android-sdk
        
        # Download and setup command line tools
        cd ~/.buildozer/android/platform/android-sdk
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip
        rm cmdline-tools.zip
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/ || true
        
        # Accept all Android licenses
        yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true
        
        # Install specific build tools version that works
        ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platforms;android-34" "platform-tools"
        
    - name: Build APK
      run: |
        source venv/bin/activate
        buildozer -v android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: novel-downloader-apk
        path: bin/*.apk
