name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zip \
          unzip \
          openjdk-11-jdk \
          git \
          python3-pip \
          wget
        
    - name: Install Buildozer
      run: |
        pip install buildozer
        
    - name: Setup Android SDK with correct paths
      run: |
        # Create Android SDK directory
        mkdir -p ~/.buildozer/android/platform/android-sdk
        
        # Download command line tools to the correct location
        cd ~/.buildozer/android/platform/android-sdk
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        rm commandlinetools-linux-9477386_latest.zip
        
        # Move to the correct directory structure (NEW STRUCTURE)
        mkdir -p cmdline-tools/latest
        mv tools/* cmdline-tools/latest/
        rm -rf tools
        
        # Set environment variables for correct paths
        echo "ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
        
        # Accept all licenses
        yes | ./cmdline-tools/latest/bin/sdkmanager --licenses
        
        # Install required components
        ./cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platforms;android-34" "platform-tools" "ndk;25.2.9519653"
        
    - name: Build APK
      run: |
        # Set the correct SDK path for Buildozer
        export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
        
        buildozer android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: novel-downloader-apk
        path: bin/*.apk
