name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zip \
          unzip \
          openjdk-11-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev
        
    - name: Install Buildozer
      run: |
        pip install buildozer
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Build APK with retry
      run: |
        # Try building with more verbose output
        buildozer -v android debug || echo "Build failed, checking logs..."
        
    - name: Check build results
      run: |
        if [ -f bin/*.apk ]; then
          echo "APK built successfully!"
          ls -la bin/
        else
          echo "No APK found. Build failed."
          exit 1
        fi
        
    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: novel-downloader-apk
        path: bin/*.apk
