name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zip \
          unzip \
          openjdk-11-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev \
          git \
          python3-setuptools
        
    - name: Install Python build dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython virtualenv
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Build APK
      run: |
        buildozer -v android debug  # Added -v for verbose output
        
    - name: Check for APK
      run: |
        if ls bin/*.apk 1> /dev/null 2>&1; then
          echo "APK built successfully!"
          ls -la bin/
        else
          echo "No APK found. Build may have failed."
          exit 1
        fi
        
    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: novel-downloader-apk
        path: bin/*.apk
